### ISSUE TITLE
Mejorar los Modelos Base de la DB

### ISSUE THREAD

**Issue by cesar-brandon** [ConsigueVentas-Team/CRM_Frontend#21]
### Tareas

- [ ] Revisar y mejorar los modelos base de la DB

**Comment by cesar-brandon** [comment]
### Tareas

- [ ] Revisar y mejorar los modelos base de la DB

**Comment by RafaDev14** [comment]
- A la tabla venta se le agregó el campo descuento (existe la posibilidad que la empresa tenga productos en ofertas) y estado para determinar si la venta fue completada, cancelada.

- También se agregó la tabla para el proveedor con sus respectivos campos.
