### ISSUE TITLE
Carga de Imágenes para Perfiles de Usuario

### ISSUE THREAD

**Issue by cesar-brandon** [ConsigueVentas-Team/CRM_Frontend#34]
### Tareas:

- [ ] Integrar react-dropzone para la carga de imágenes
- [ ] Mostrar las imágenes como avatares en la tabla correspondiente
- [ ] Implementar visualización de imágenes en el detalle del usuario
- [ ] Mostrar la imagen del usuario actual en la parte superior del sistema
- [ ] Mostrar la imagen del usuario en "ver perfil"

**Comment by CarlosRaul04** [comment]
He agregado cargar usuario y he hecho que se vean los avatar en caso no haya foto de perfil
