### ISSUE TITLE
Editar imagen de perfil

### ISSUE THREAD

**Issue by HansUrpay** [ConsigueVentas-Team/CRM_Frontend#39]
### Características
- Restringir los permisos para que solo el administrador pueda actualizar la imagen de perfil del usuario.
- Hacer validaciones:
    - Límite de tamaño máximo de archivo.
    - No permitir dejar el campo vacío sin archivo.
    - No permitir que suban más de un archivo.

**Comment by CarlosRaul04** [comment]
se ha implementado correctamente la actualización de imagen de perfil de usuario
